/**
 * KHUSHAL LABS - Central Command Center Project Dataset
 * Paper Style & Colorful Laboratory Theme Edition with Real UI Screenshots
 */

const PROJECTS_DATA = [
  {
    id: "apex-market",
    number: "01",
    name: "ApexMarket",
    subtitle: "Modern Digital Marketplace",
    category: "Web",
    categoryLabel: "Marketplace / Web",
    description: "A modern digital marketplace project designed to provide a clean and scalable shopping experience.",
    technologies: ["HTML", "CSS", "JavaScript", "Web"],
    liveUrl: "https://apexmarketstore.vercel.app/",
    buttonText: "OPEN PROJECT",
    featured: true,
    featuredRank: 2,
    status: "ONLINE",
    image: "assets/apex-market.jpg",
    // Paper Theme Styling
    paperColor: "#ecfdf5", // Mint pastel
    accentColor: "#059669",
    borderAccent: "#10b981",
    tapeColor: "rgba(16, 185, 129, 0.35)",
    tapeRotation: "-2.5deg",
    cardRotation: "-1deg",
    doodle: "🛍️",
    note: "Clean storefront & checkout flow!",
    abstractType: "market"
  },
  {
    id: "my-portfolio",
    number: "02",
    name: "My Portfolio",
    subtitle: "Developer Identity & Showcase",
    category: "Web",
    categoryLabel: "Portfolio / Web",
    description: "My personal developer portfolio showcasing my projects, skills, experience and technical journey.",
    technologies: ["HTML", "CSS", "JavaScript", "Web"],
    liveUrl: "https://webkhushal-nu.vercel.app",
    buttonText: "OPEN PORTFOLIO",
    featured: false,
    status: "ONLINE",
    image: "assets/my-portfolio.jpg",
    paperColor: "#f5f3ff", // Lavender pastel
    accentColor: "#7c3aed",
    borderAccent: "#8b5cf6",
    tapeColor: "rgba(139, 92, 246, 0.35)",
    tapeRotation: "3deg",
    cardRotation: "1.2deg",
    doodle: "✨",
    note: "Personal story & skills archive",
    abstractType: "portfolio"
  },
  {
    id: "built-in-tools",
    number: "03",
    name: "Built-in Tools",
    subtitle: "Everyday Web Utilities",
    category: "Tools",
    categoryLabel: "Tools",
    description: "A collection of useful built-in web utilities designed to make everyday tasks faster and easier.",
    technologies: ["JavaScript", "Web Tools", "Utilities"],
    liveUrl: "https://webkhushal.vercel.app/",
    buttonText: "OPEN TOOLS",
    featured: false,
    status: "ONLINE",
    image: "assets/built-in-tools.jpg",
    paperColor: "#fefce8", // Sunny pastel
    accentColor: "#ca8a04",
    borderAccent: "#eab308",
    tapeColor: "rgba(234, 179, 8, 0.4)",
    tapeRotation: "-1.5deg",
    cardRotation: "-0.8deg",
    doodle: "🛠️",
    note: "Super handy quick web utilities",
    abstractType: "tools"
  },
  {
    id: "spydy-reminder",
    number: "04",
    name: "Spydy Reminder",
    subtitle: "Desktop Notification System",
    category: "Productivity",
    categoryLabel: "Desktop / Productivity",
    description: "A productivity reminder application designed for quick reminders and desktop-focused workflows.",
    technologies: ["Electron", "JavaScript", "Desktop", "Productivity"],
    liveUrl: "https://khushal-jangid.github.io/spydy-electron/",
    buttonText: "OPEN PROJECT",
    featured: false,
    status: "ONLINE",
    image: "assets/spydy-reminder.jpg",
    paperColor: "#fff7ed", // Peach pastel
    accentColor: "#ea580c",
    borderAccent: "#f97316",
    tapeColor: "rgba(249, 115, 22, 0.35)",
    tapeRotation: "2deg",
    cardRotation: "1.5deg",
    doodle: "⏰",
    note: "Never miss a deadline or task!",
    abstractType: "reminder"
  },
  {
    id: "apex-studio",
    number: "05",
    name: "Apex Studio",
    subtitle: "Creative Web Development Lab",
    category: "Web",
    categoryLabel: "Web Development",
    description: "A web development project focused on building and experimenting with modern website experiences.",
    technologies: ["HTML", "CSS", "JavaScript", "Web Design"],
    liveUrl: "https://apex-studio-dev.surge.sh/index.html#",
    buttonText: "OPEN STUDIO",
    featured: false,
    status: "ONLINE",
    image: "assets/apex-studio.jpg",
    paperColor: "#fdf2f8", // Rose pastel
    accentColor: "#db2777",
    borderAccent: "#ec4899",
    tapeColor: "rgba(236, 72, 153, 0.35)",
    tapeRotation: "-3deg",
    cardRotation: "-1.4deg",
    doodle: "🎨",
    note: "Experimental UI & layouts lab",
    abstractType: "studio"
  },
  {
    id: "toolbox-suite",
    number: "06",
    name: "ToolBox Suite",
    subtitle: "Multi-Purpose Developer Hub",
    category: "Tools",
    categoryLabel: "Developer Tools",
    description: "A multi-purpose toolbox containing useful utilities for developers and everyday digital workflows.",
    technologies: ["JavaScript", "Utilities", "Web Tools", "Developer Tools"],
    liveUrl: "https://khushal-jangid.github.io/toolbox-suite/",
    buttonText: "OPEN TOOLBOX",
    featured: true,
    featuredRank: 4,
    status: "ONLINE",
    image: "assets/toolbox-suite.jpg",
    paperColor: "#f0f9ff", // Sky pastel
    accentColor: "#0284c7",
    borderAccent: "#0ea5e9",
    tapeColor: "rgba(14, 165, 233, 0.35)",
    tapeRotation: "2.5deg",
    cardRotation: "1deg",
    doodle: "🧰",
    note: "The Swiss army knife for coders",
    abstractType: "toolbox"
  },
  {
    id: "pulse-remote-pc",
    number: "07",
    name: "PulseRemote PC",
    subtitle: "Low-Latency Remote Controller",
    category: "Systems",
    categoryLabel: "Systems / Remote Control",
    description: "A remote PC control project focused on connecting and controlling computer workflows through a modern interface.",
    technologies: ["Systems", "Networking", "Remote Control", "Web"],
    liveUrl: "https://khushal-jangid.github.io/pulse-remote-pc/#",
    buttonText: "OPEN PULSE",
    featured: true,
    featuredRank: 3,
    status: "ONLINE",
    image: "assets/pulse-remote-pc.jpg",
    paperColor: "#fef2f2", // Coral Red pastel
    accentColor: "#dc2626",
    borderAccent: "#ef4444",
    tapeColor: "rgba(239, 68, 68, 0.35)",
    tapeRotation: "-2deg",
    cardRotation: "-1.2deg",
    doodle: "⚡",
    note: "Seamless wireless PC controller",
    abstractType: "systems"
  },
  {
    id: "folio-notes",
    number: "08",
    name: "Folio",
    subtitle: "Paper Notes & Daily Tasks",
    category: "Productivity",
    categoryLabel: "Productivity",
    description: "A paper-inspired notes and daily task experience designed to combine simplicity with a modern digital workflow.",
    technologies: ["Productivity", "Web App", "Task Manager", "UI/UX"],
    liveUrl: "https://folio-notes-tasks.surge.sh/download.html",
    buttonText: "OPEN FOLIO",
    featured: false,
    status: "ONLINE",
    image: "assets/folio-notes.jpg",
    paperColor: "#fffbeb", // Warm Kraft amber
    accentColor: "#b45309",
    borderAccent: "#f59e0b",
    tapeColor: "rgba(245, 158, 11, 0.4)",
    tapeRotation: "1.8deg",
    cardRotation: "0.9deg",
    doodle: "📝",
    note: "Paper-feel daily notes experience",
    abstractType: "notes"
  },
  {
    id: "aura-os",
    number: "09",
    name: "AURA OS",
    subtitle: "AI Agent Workspace",
    category: "AI",
    categoryLabel: "AI / Agent",
    description: "An AI agent workspace concept designed around intelligent assistants, workflows and AI-powered productivity.",
    technologies: ["AI", "Agents", "Productivity", "Web"],
    liveUrl: "https://auraagentai.vercel.app/",
    buttonText: "OPEN AURA OS",
    featured: true,
    featuredRank: 1,
    status: "ONLINE",
    image: "assets/aura-os.jpg",
    paperColor: "#faf5ff", // Royal Violet pastel
    accentColor: "#6b21a8",
    borderAccent: "#9333ea",
    tapeColor: "rgba(147, 51, 234, 0.4)",
    tapeRotation: "-3.5deg",
    cardRotation: "-1.5deg",
    doodle: "🤖",
    note: "Autonomous AI workspace engine!",
    abstractType: "ai-os"
  },
  {
    id: "private-chat",
    number: "10",
    name: "Private Chat",
    subtitle: "Encrypted & Minimal Messaging",
    category: "Communication",
    categoryLabel: "Communication / Privacy",
    description: "A privacy-focused chat application designed around simple and private conversations.",
    technologies: ["Web", "Messaging", "Privacy", "Real-time"],
    liveUrl: "https://privateschat.lovable.app/",
    buttonText: "OPEN CHAT",
    featured: false,
    status: "ONLINE",
    image: "assets/private-chat.jpg",
    paperColor: "#f0fdfa", // Mint/Teal pastel
    accentColor: "#0f766e",
    borderAccent: "#14b8a6",
    tapeColor: "rgba(20, 184, 166, 0.35)",
    tapeRotation: "2.2deg",
    cardRotation: "1.3deg",
    doodle: "🔒",
    note: "Zero noise, secure conversations",
    abstractType: "chat"
  },
  {
    id: "indian-agent",
    number: "11",
    name: "IndianAgent",
    subtitle: "Intelligent Conversational AI",
    category: "AI",
    categoryLabel: "AI / Chatbot",
    description: "An AI chatbot project focused on building an intelligent conversational experience.",
    technologies: ["AI", "Conversational Agent", "Web", "NLP"],
    liveUrl: "https://indianagent.lovable.app/",
    buttonText: "OPEN INDIANAGENT",
    featured: false,
    status: "ONLINE",
    image: "assets/indian-agent.jpg",
    paperColor: "#fff7ed", // Saffron / Warm Amber
    accentColor: "#c2410c",
    borderAccent: "#ea580c",
    tapeColor: "rgba(234, 88, 12, 0.4)",
    tapeRotation: "-1.8deg",
    cardRotation: "-1deg",
    doodle: "🇮🇳",
    note: "Conversational intelligence agent",
    abstractType: "chatbot"
  }
];

// Visual Categories mapping
const CATEGORIES_DATA = [
  {
    id: "AI",
    name: "AI",
    count: 2,
    paperColor: "#faf5ff",
    badgeColor: "#9333ea",
    doodle: "🤖",
    icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a8 8 0 0 0-8 8c0 3.36 2.07 6.24 5 7.42V20a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-2.58c2.93-1.18 5-4.06 5-7.42a8 8 0 0 0-8-8z"/><line x1="9" y1="9" x2="9.01" y2="9"/><line x1="15" y1="9" x2="15.01" y2="9"/></svg>`,
    description: "Intelligent autonomous agents & conversational models",
    projects: ["AURA OS", "IndianAgent"]
  },
  {
    id: "Web",
    name: "Web",
    count: 3,
    paperColor: "#ecfdf5",
    badgeColor: "#10b981",
    doodle: "🌐",
    icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>`,
    description: "Modern digital marketplaces, studios and portals",
    projects: ["ApexMarket", "Portfolio", "Apex Studio"]
  },
  {
    id: "Tools",
    name: "Tools",
    count: 2,
    paperColor: "#fefce8",
    badgeColor: "#eab308",
    doodle: "🧰",
    icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>`,
    description: "Everyday web utilities and developer multi-tools",
    projects: ["Built-in Tools", "ToolBox Suite"]
  },
  {
    id: "Productivity",
    name: "Productivity",
    count: 2,
    paperColor: "#fffbeb",
    badgeColor: "#f59e0b",
    doodle: "📌",
    icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>`,
    description: "Paper-inspired task flows and desktop reminders",
    projects: ["Spydy Reminder", "Folio"]
  },
  {
    id: "Systems",
    name: "Systems",
    count: 1,
    paperColor: "#fef2f2",
    badgeColor: "#ef4444",
    doodle: "⚡",
    icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>`,
    description: "Remote PC control and computer workflows",
    projects: ["PulseRemote PC"]
  },
  {
    id: "Communication",
    name: "Communication",
    count: 1,
    paperColor: "#f0fdfa",
    badgeColor: "#14b8a6",
    doodle: "💬",
    icon: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>`,
    description: "Private conversations and secure messaging",
    projects: ["Private Chat"]
  }
];

// Tech stack chips with colorful paper sticker colors
const TECH_STACK = [
  { name: "HTML", category: "Core Web", color: "#ffedd5", border: "#f97316" },
  { name: "CSS", category: "Styling", color: "#e0f2fe", border: "#0ea5e9" },
  { name: "JavaScript", category: "Language", color: "#fef9c3", border: "#eab308" },
  { name: "React", category: "Frontend", color: "#e0e7ff", border: "#6366f1" },
  { name: "Python", category: "Language", color: "#ecfdf5", border: "#10b981" },
  { name: "AI", category: "Intelligence", color: "#f3e8ff", border: "#a855f7" },
  { name: "Git", category: "VCS", color: "#fee2e2", border: "#ef4444" },
  { name: "GitHub", category: "Platform", color: "#f1f5f9", border: "#475569" },
  { name: "Vercel", category: "Cloud", color: "#ffffff", border: "#1e1e24" },
  { name: "Electron", category: "Desktop", color: "#e0f2fe", border: "#38bdf8" },
  { name: "AWS", category: "Cloud", color: "#ffedd5", border: "#f59e0b" },
  { name: "Docker", category: "Containers", color: "#e0f7fa", border: "#00acc1" }
];

// Export for Node environments if present
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROJECTS_DATA, CATEGORIES_DATA, TECH_STACK };
}
